<Inputpage>:
    
    MDScreen:
        name: "input"
        md_bg_color: 0,22,22,1
        #NavBar:
        Drawe:

        MDBoxLayout:
            orientation:"vertical"
            size_hint_y: None
            height:"100dp"
                
            Button:
                id: tts
                text: 'Touch to speak'
                on_release: root.listener()
            
                    
            

